### ISSUE TITLE
Add support to poll specific FIFO partitions

### ISSUE THREAD

**Issue by jsumners** [knockaway/sqsiphon#5]
Currently, the poller asks SQS for the next 10 available messages regardless of partition. When _many_ messages are in a single partition, this causes delay in processing other partitions. The poller should be able to be configured such that it will poll a single or list of partitions.

**Comment by jsumners** [comment]
This is not possible. Amazon SQS does not provide facility for requesting messages with a specific group id. See:

+ https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_ReceiveMessage.html
+ https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/SQS.html#receiveMessage-property

**Comment by ap0** [comment]
Just so I'm on the same page, is the issue that you might have partitions A-D, and you might have a partitioning/hashing scheme that doesn't partition messages relatively equally, so maybe A has 500 messages and the others have 5, and the consumer isn't able to do any prioritization and just keeps processing messages in the order SQS delivers them, thus making it so other partitions cannot be prioritized?

**Comment by jsumners** [comment]
@ap0 that is correct.

**Comment by ap0** [comment]
From the docs:

>Partition management occurs automatically in the background and is transparent to your applications. Your queue and messages are available at all times.

I think this is the crux of the issue -- you really have no control over how partitioning works, it's just a hint for how SQS should partition things in the background when it decides it needs to scale.  In something like Kafka or Kinesis, you can explicitly declare how many partitions/shards you want, and then your consumers can be bound to a specific partition based on how you want processing to work.  This is just a fundamental difference in SQS design.

Your proposed solution here https://github.com/knockaway/webhooks-processor/issues/146 seems like the right one -- specific queues that you can prioritize independently.  SQS's "simple" mechanics make it such that you can't have any sort of sophisticated consumer mechanism.
